name: Gradle Tests (CI)

on: push

jobs:
  jar:
    name: Test with Gradle
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: "8.0.282"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test JAR with Gradle
        run: ./gradlew test
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

